#+TITLE: Readme

* Units in megastrike
Units in megastrike are built using lisp functions. If you don't know lisp,
that's OK. It isn't too difficult to create your own.
* The Unit file
Units are placed in files named with the full unit name (=locust-lct-1v.lisp=). Variants on a design should be placed in their own files. They can be created by copying an existing variant and changing the numbers. Below is an example entry, taken from the =locust-lct-1v.lisp= file, with additional annotations.
** The file structure
The first line should not be changed. Without it, the function which creates the unit cannot find the correct class and helper functions.

#+begin_src lisp
(in-package :megastrike)

#+end_src

Here begins the actual creation of the unit. Most elements are self-explanatory but there are a few catches.

After the defun should be the unit's name and designation.

Notice that for short-name and long-name, there is a colon in front. That is ncessarly to make the function work, make sure not to remove any of those.
#+begin_src lisp
(add-or-update-mek
 :short-name "LCT-1V"
 :long-name "Locust LCT-1V"
 :unit-type "BM"
 :role "Scout"
 :pv 18
 :size 1
 :armor 2
 :structure 2
 :mv-string "8"
 #+end_src

Moves should be entered as a string and in Hexes, not inches (so a mech like the locust, with 16" move should be "8"). If it can jump, like the Phoenix hawk, it should be "6j", note the lowercase. If it has two (For mech like the Shadow Hawk, which has 5 walk / 3 jump), then it would be "5/3j".

 #+begin_src lisp
 :short 1
 :medium 1
 :long 0 ;; Enter 0.5 for 0*
 :ov 0
#+end_src

Technically speaking, order does not matter. But for simplicity's sake, please follow this order. Note for units which have the 0* damage code, you should enter 0.5. The program will detect that and handle it appropriately (rolling to see if you do 0 or 1 damage).

The specials is just a string listing all the specials separated by spaces. Each special should match the code in table at the end of Alphastrike exactly (including capitalization). All Battlemechs should have "SRCH SOA", add any other specials after those two (For example "SRCH SOA AC2/2/0").

The images I am using are the same images (in the same directory structure) as Megamek. Check the =data/images/units/*= folder of your Megamek install for the file name. Also, please copy the image into the same location in Megastrike as Megamek has kindly given permission for me to use their images.

#+begin_src lisp
 :specials "SRCH SOA"
 :display "data/images/units/mechs/Locust.png"
#+ end_src

Finally,the TRO entry. I grabbed this from the MTF file in my Megamek installation, but there are other sources as well. If you don't have it, just put an empty string: =""=
#+begin_src lisp
 :tro
"Overview: The Locust is undoubtedly one of the most popular and prevalent
light BattleMechs ever made. First produced in 2499, the almost dozen distinct
factories manufacturing the design quickly spread the design to every power in
human space. Its combination of tough armor (for its size), exceptional speed,
and most importantly, low cost have all contributed to the Locust's success. It
remains the benchmark for many scouting designs, and its continual upgrades have
ensured that it remains just as effective with every new conflict that appears.

Capabilities: As the Locust was first developed as a recon platform, speed is
paramount to the design's philosophy. While many variants change the weaponry to
fill specific tasks or purposes, Locusts are nearly always pressed into service
in ways where they can best take advantage of their speed. When in line
regiments, they can act as a deadly flankers or harassers, and are often used in
reactionary roles to quickly plug holes in a fluid battle line. The structural
form of Locusts themselves are their greatest weakness; with no hands, they are
disadvantaged in phyisical combat and occasionally have difficulty righting
themselves after a fall.

Deployment: One of the most common designs even produced, even the smallest
mercenary or pirate outfits will often field one or more of the design.
Production for the Locust has continued uninterrupted for centuries, and it
plays an important role in the militaries of many smaller nations. The base
LCT-1V was once estimated to account for more than 75% of all Locusts in
existence at the end of the Succession Wars, though these numbers have dropped
with the reappearance of more advanced technology. Still, it remains common in
every military worth note.

systemmanufacturer:CHASSIS:Bergan
systemmode:CHASSIS:VII
systemmanufacturer:ENGINE:LTV
systemmode:ENGINE:160
systemmanufacturer:ARMOR:StarSlab
systemmode:ARMOR:/1
systemmanufacturer:COMMUNICATIONS:Garrett
systemmode:COMMUNICATIONS:T10-B
systemmanufacturer:TARGETING:O/P
systemmode:TARGETING:911 "
)
#+end_src

Balanced parentheses is important, ensure that there is a parentheses after the TRO string to close the whole expression.

When you open megastrike, it scans the =data= folder and all its subfolders for lisp files and loads them, so the unit should appear immediately when you restart megastrike. To use them, you can add them in the army builder.

If it does not work or there is an error, there is probably an error in the file. Contact me and I'll be happy to try to help!
