* Plan for a computer based AS game.
Swap to Beast for an ECS system rather than what I currently have?

I think this would really clean up elements a lot, but I'll need to think hard about how to define different aspects.
** Aspect Design for Elements

*** ID Info
The Elements's name, the Elements's model info, The Elements's type, the Element's role, point-value, size
*** Damageable
Current/Max armor, Current/Max structure, Critical hits info
*** Moveable
move-alist
**** Moves are an alist
Format below:
#+begin_src lisp
((:walk . 4) (:jump . 4))
#+end_src

This can be accessed using:
#+begin_src lisp
(assoc :walk *move-alist*)
#+end_src

This returns ~nil~ if the unit doesn't have the the appropriate move-type
*** Attack
Short, Medium, Long
*** Heat
OV, current Heat
*** Specials
specials (this will literally just be a dumb list for now)
*** Display
image path
*** Location
q, r, s
*** Pilot
name, skill
** Entities
Elements default Location and Pilot values to nil to begin with
* Point Release plan
** 0.1.0
*** Next Steps
**** Map
Highlight on mouse over, info on click.

Zooming.

Refactor code so it makes better sense (similar to how we did unit cards).
**** Units
Add units to the map.

Make the units presentation types.
**** Movement
Calculate movement as simple straight-line distance (I can use this calculation for range later).
**** Attack
Roll to hit.
Roll for damage.

Manage screen updates.
** 0.1.1
*** Planned Expansion
**** Map
The hex drawing is confusing and needs to be cleaned up. I also don't like the positioning of the hex number.

Make presentation types for the minimap hexes (if necessary).
