#!/bin/sh
docker run \
    -v .:/app:z \
    -u 0 \
    fedora:latest \
    sh -c "
    whoami
    dnf install -y sudo
    mkdir -p /app/build_data/home
    useradd -u $(id -u) -d /app/build_data/home builduser
    echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
    chown -R $(id -u) /app
    cd /app
    export GITHUB_ACTION='test'
    su builduser - scripts/unix-release"

