name: build-macos-release
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'
  #     - 'master'
  # pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: scripts/unix-dependencies
      - name: Run build
        run: ./install.sh
      - name: Update path
        run: source ~/.zshrc
      - name: Archive distributable
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ./
